export const ONBOARD_ENGLISH: Readonly<Record<string, string>> = {
  "SAP 개발 환경 시작하기": "Set up SAP ABAP MCP",
  "이 PC에서만 실행 중": "Running only on this computer",
  "PC 확인": "Check computer",
  "설치 상태 점검": "Check installed tools",
  "SAP 연결": "Connect SAP",
  "로그인 및 검증": "Sign in and verify",
  "도구 연결": "Connect AI tools",
  "MCP 자동 설정": "Register MCP",
  "완료": "Finish",
  "바로 시작": "Start using SAP",
  "Step 1 · PC 확인": "Step 1 · Check computer",
  "필요한 준비가 되어 있는지 먼저 확인할게요.": "Let's check that your computer is ready.",
  "설치된 항목은 그대로 사용하고, 부족한 부분만 안내합니다. 기존 설정 파일은 덮어쓰지 않습니다.": "We reuse installed tools and guide you through anything missing. Existing configuration files are preserved.",
  "자동 점검 결과": "Automatic checks",
  "Claude 또는 Codex 중 하나만 준비되어 있어도 계속할 수 있습니다.": "You can continue with either Claude or Codex installed.",
  "설정 파일 상세 보기": "View configuration files",
  "다시 확인": "Check again",
  "SAP 연결 설정": "Set up SAP connection",
  "사용할 SAP 시스템": "Choose your SAP system",
  "저장된 연결이 있으면 다시 확인해 사용하고, 없으면 새로 추가하세요.": "Verify a saved connection or add a new one.",
  "새 연결 추가": "Add a new connection",
  "인증 방식": "Authentication method",
  "SAP ID · 비밀번호": "SAP user ID and password",
  "BTP ABAP 서비스 키 가져오기": "Import BTP ABAP service key",
  "브라우저 로그인 · OAuth PKCE": "Browser sign-in · OAuth PKCE",
  "OAuth 클라이언트 인증": "OAuth client credentials",
  "회사에서 허용한 인증 방식을 선택하세요.": "Choose an authentication method permitted by your company.",
  "연결 이름": "Connection name",
  "이 SAP 시스템을 구분할 짧은 이름": "A short name to identify this SAP system",
  "SAP 클라이언트": "SAP client",
  "SAP 사용자 ID": "SAP user ID",
  "SAP 비밀번호": "SAP password",
  "BTP 서비스 키 JSON": "BTP service key JSON",
  "SAP URL·클라이언트·토큰 주소를 자동으로 설정합니다. 저장 뒤 원본 파일도 안전하게 관리하세요.": "Fills in the SAP URL, client and token endpoint. Keep the original service key file secure after saving.",
  "OAuth 토큰 URL": "OAuth token URL",
  "OAuth 로그인 URL": "OAuth authorization URL",
  "OAuth Scope · 선택": "OAuth scope · optional",
  "브라우저 로그인은 관리자에게 등록된 네이티브 OAuth 클라이언트와 127.0.0.1 콜백이 필요합니다. 회사 SAML·Kerberos SSO와의 호환성은 인증 제공자 설정에 따라 달라집니다.": "Browser sign-in requires a registered native OAuth client and a 127.0.0.1 callback. Compatibility with company SAML or Kerberos SSO depends on your identity provider configuration.",
  "언어": "SAP language",
  "한국어 (KO)": "Korean (KO)",
  "시스템 구분": "System environment",
  "운영 — 읽기 전용": "Production — read only",
  "변경 허용 패키지": "Packages allowed for changes",
  "자격 증명은 이 PC에서 인증 확인에 사용하고 macOS Keychain 또는 Windows DPAPI로 보호합니다. 브라우저 로그인은 별도 창에서 진행하며, 토큰과 서비스 키는 AI 대화에 입력하지 마세요.": "Credentials are verified on this computer and protected with macOS Keychain or Windows DPAPI. Browser sign-in opens a separate window. Keep tokens and service keys out of AI conversations.",
  "SAP URL·클라이언트·ADT 권한을 모르면 SAP 관리자에게 확인하세요.": "Ask your SAP administrator if you do not know the SAP URL, client or ADT permissions.",
  "OAuth·BTP 고급 인증 안내": "OAuth and BTP authentication guide",
  "이전": "Back",
  "연결 확인 후 저장": "Verify connection and save",
  "인증 취소": "Cancel authentication",
  "AI 도구에 SAP 연결하기": "Connect SAP to your AI tools",
  "선택한 SAP 연결과 현재 설치본을 확인합니다. 기존 등록은 보존하고, 다른 설정이면 수정할 값을 안내합니다.": "Checks the selected SAP connection and current installation. Existing registrations are preserved; different settings show the values to review.",
  "등록 설정 확인 필요": "Review registration",
  "기존 등록이 선택한 연결 또는 현재 실행 설정과 다릅니다. 기존 설정은 변경하지 않았습니다.": "The existing registration differs from the selected connection or current runtime settings. Existing settings have not been changed.",
  "등록은 있지만 선택한 연결의 실행 설정을 비교하지 못했습니다. 완료 전에 설정을 확인하세요.": "A registration exists, but its runtime settings could not be compared with this connection. Review them before finishing.",
  "실행파일 또는 API 버전": "Runtime file or API version",
  "SAP 연결 이름": "SAP connection name",
  "프로필 저장 위치": "Profile directory",
  "사용 중지 또는 승인 대기": "Disabled or awaiting approval",
  "AI 도구의 MCP 설정에서 아래 값을 확인한 뒤 다시 확인하세요. 다른 시작 옵션과 권한 설정은 유지하세요.": "Review the values below in your AI tool's MCP settings, then check again. Keep other startup options and permission settings.",
  "이 연결에 필요한 값 보기": "View required connection values",
  "MCP 설정 안내 열기": "Open MCP configuration guide",
  "새 등록의 도구 모드": "Tool mode for new registrations",
  "토큰 절약 — 5개 도구 (기본)": "Save tokens — 5 tools (default)",
  "자주 쓰는 도구 바로 호출 — 17개 도구": "Direct access to common tools — 17 tools",
  "최소 노출 — 1개 도구": "Smallest tool list — 1 tool",
  "세 모드 모두 같은 기능에 접근합니다. 초기 도구가 적으면 고정 토큰이 줄지만 기능 탐색 호출이 늘 수 있습니다. 1개 도구 모드는 읽기에도 승인 요청이 표시될 수 있습니다. 기존 등록에는 적용되지 않습니다.": "All three modes access the same capabilities. Fewer initial tools reduce fixed tokens but may require more discovery calls. The one-tool mode may show approval prompts even for reads. Existing registrations are preserved.",
  "설정 완료": "Finish setup",
  "등록을 마쳤습니다.": "Registration complete.",
  "Claude 또는 Codex를 다시 열고 아래 문구를 새 대화에 붙여넣으세요. SAP 시스템 정보가 조회되면 AI 도구에서도 실제 접속이 확인됩니다. 이 창과 터미널은 닫아도 됩니다.": "Reopen Claude or Codex and paste the prompt below into a new conversation. A successful SAP system query verifies actual access from your AI tool. You can close this window and terminal.",
  "첫 SAP 조회 문구": "First SAP query prompt",
  "첫 조회 문구 복사": "Copy first query prompt",
  "설정 단계": "Setup steps",
  "사번 또는 SAP ID": "Employee number or SAP user ID",
  "BTP에서 발급받은 ABAP 환경 서비스 키 JSON": "ABAP Environment service key JSON from BTP",
  "Step 2 · SAP 연결": "Step 2 · Connect SAP",
  "SAP 연결과 인증 방식을 설정합니다.": "Set up your SAP connection and authentication.",
  "입력한 정보는 이 PC에서 직접 SAP로 확인합니다. 연결에 성공한 뒤에만 안전하게 저장합니다.": "Your connection is verified directly from this computer. Credentials are saved securely only after the connection succeeds.",
  "Step 3 · 도구 연결": "Step 3 · Connect AI tools",
  "한 번만 연결하면 다음부터 바로 사용할 수 있어요.": "Connect once, then use SAP from your AI tool.",
  "공식 Claude와 Codex 명령으로 MCP를 등록합니다. 이미 같은 연결이 있으면 변경하지 않습니다.": "Registers MCP with the official Claude and Codex commands. Existing registrations for this connection are preserved.",
  "Step 4 · 완료": "Step 4 · Finish",
  "첫 SAP 조회로 연결을 확인하세요.": "Verify the connection with your first SAP query.",
  "요청을 처리하지 못했습니다.": "The request could not be completed.",
  " SAP 시스템의 연결 상태와 시스템 정보를 조회해 줘. 설정 목록만으로 접속 성공이라고 판단하지 말고 실제 시스템 조회 결과를 보여 줘. 소스 수정이나 데이터 조회는 하지 마.": " Query the connection status and system information for this SAP system. Show an actual system query result; a saved configuration alone does not prove access. Do not modify source code or query business data.",
  "확인 필요": "Needs checking",
  "설치됨": "Installed",
  "설치가 필요합니다": "Installation required",
  "있음": "Present",
  "없음": "Missing",
  "현재 운영체제에서는 웹 온보딩으로 비밀번호를 안전하게 저장할 수 없습니다. Windows 또는 macOS에서 실행하세요.": "This operating system cannot securely save credentials through browser setup. Run this on Windows or macOS.",
  "Claude Code 또는 Codex를 설치한 뒤 ‘다시 확인’을 눌러주세요. 계속 찾지 못하면 터미널을 새로 열어 onboard를 다시 실행하세요. ": "Install Claude Code or Codex, then select Check again. If it is still missing, open a new terminal and run onboard again. ",
  "Claude 설치 안내": "Claude installation guide",
  "Codex 설치 안내": "Codex installation guide",
  "연결 확인": "Verify connection",
  "인증 다시 설정": "Set up authentication again",
  "HTTP 인증 필요": "HTTP authentication required",
  "확인 중…": "Checking…",
  " 저장된 설정은 유지됩니다.": " Saved settings are preserved.",
  "설정·인증 수정": "Edit settings and authentication",
  "기존 설정을 불러왔습니다. 선택한 방식으로 다시 인증하면 기존 권한 설정을 보존해 저장합니다.": "Saved settings loaded. Authenticating again with the selected method preserves your existing access policy.",
  "확인 실패": "Check failed",
  "연결 실패": "Connection failed",
  "인증 필요": "Authentication required",
  "MCP 연결 확인": "MCP connection verified",
  "등록됨": "Registered",
  "설정 필요": "Setup needed",
  "설치 필요": "Installation needed",
  "MCP 서버 연결이 확인됐습니다. SAP 접속은 시스템 조회로 확인하세요.": "The MCP server connection is verified. Run a system query to verify SAP access.",
  "SAP ABAP MCP가 등록되어 있습니다. 실제 연결 성공은 아직 확인되지 않았습니다.": "SAP ABAP MCP is registered. An actual connection has not yet been verified.",
  "버전 ": "Version ",
  "확인됨": "Verified",
  "먼저 공식 설치 안내를 따라 설치하세요.": "Follow the official installation guide first.",
  "기존 MCP 설정을 읽지 못했습니다: ": "Could not read the existing MCP configuration: ",
  "AI 도구에서 MCP 인증을 완료한 뒤 다시 확인하세요.": "Complete MCP authentication in your AI tool, then check again.",
  "AI 도구의 MCP 오류에서 실행 파일 경로와 서버 시작 로그를 확인한 뒤 다시 확인하세요.": "Check the executable path and server startup logs in your AI tool's MCP error, then check again.",
  "SAP 연결하기": "Connect SAP",
  "설치 안내 열기": "Open installation guide",
  "연결 중…": "Connecting…",
  "등록을 완료했습니다. 실제 연결 상태는 아래 진단을 확인하세요.": "Registration complete. Check the diagnostics below for the actual connection status.",
  "기존 설정과 자격 증명은 유지됩니다. 인증 방식을 확인하고 다시 시도하세요.": "Existing settings and credentials are preserved. Check the authentication method and try again.",
  "ABAP 환경 서비스의 서비스 키 JSON을 확인하세요.": "Check the service key JSON for the ABAP Environment service.",
  "현재는 Client Secret을 포함한 서비스 키를 지원합니다. 인증서 방식은 관리자와 별도 설정을 확인하세요.": "Service keys containing a Client Secret are supported. Ask your administrator about separate configuration for certificate authentication.",
  "로그인 창을 완료한 뒤 다시 시도하세요. 관리자가 네이티브 클라이언트의 루프백 콜백을 허용했는지 확인하세요.": "Complete the sign-in window and try again. Check that your administrator allowed a loopback callback for the native client.",
  "로그인을 다시 시작하고, 관리자에게 Client ID·콜백·로그인 URL을 확인하세요.": "Restart sign-in and ask your administrator to check the Client ID, callback and authorization URL.",
  "Token URL·Client ID·Scope·Client Secret과 회사 인증서를 확인하세요.": "Check the Token URL, Client ID, Scope, Client Secret and company certificates.",
  "기존 연결과 같은 인증 방식을 선택하거나 새 연결 이름을 사용하세요.": "Use the saved connection's authentication method or choose a new connection name.",
  "SAP 계정과 클라이언트 번호를 확인하세요. 회사 SSO 전용 계정이면 고급 인증 안내를 사용하고 비밀번호를 반복 입력하지 마세요.": "Check your SAP account and client number. For an SSO-only account, use the advanced authentication guide instead of repeatedly entering a password.",
  "SAP 관리자에게 이 계정의 ADT 권한과 /sap/bc/adt 서비스 상태를 확인해 달라고 요청하세요.": "Ask your SAP administrator to check this account's ADT permissions and the /sap/bc/adt service.",
  "VPN·SAP URL·서버 상태를 확인하세요. 인증서를 신뢰하지 못하는 경우 회사 인증서 설정을 확인하세요.": "Check your VPN, SAP URL and server status. For certificate trust failures, check your company certificate configuration.",
  "오류 내용에 맞춰 VPN·SAP URL·회사 인증서 설정을 확인하세요. 저장된 설정은 유지됩니다.": "Check your VPN, SAP URL and company certificates based on the error. Saved settings are preserved.",
  "연결 이름은 영문·숫자·밑줄·하이픈, URL은 HTTPS, 클라이언트는 숫자로 입력하세요.": "Use letters, numbers, underscores or hyphens for the connection name, an HTTPS URL and a numeric SAP client.",
  "AI 도구의 MCP 설정을 읽을 수 없습니다. 해당 도구의 오류를 해결한 뒤 다시 확인하세요.": "The AI tool's MCP configuration could not be read. Resolve its configuration error, then check again.",
  "AI 도구의 MCP 등록 명령이 실패했습니다. 실행 경로와 권한을 확인한 뒤 다시 시도하세요.": "The AI tool's MCP registration command failed. Check its executable path and permissions, then try again.",
  "등록 명령 뒤 설정을 찾지 못했습니다. AI 도구의 MCP 목록을 확인하세요.": "Could not find the configuration after registration. Check the AI tool's MCP list.",
  "설정 저장과 비밀번호 복원에 실패했습니다. 저장된 연결을 선택해 비밀번호를 다시 입력하세요.": "Saving the configuration and restoring the credential both failed. Select the saved connection and enter its credential again.",
  "인증 취소를 요청했습니다. 처리 중인 연결 확인이 끝나면 다시 시도할 수 있습니다.": "Authentication cancellation requested. You can try again when the current connection check ends.",
  "브라우저 로그인 대기 중…": "Waiting for browser sign-in…",
  "SAP 연결 확인 중…": "Checking SAP connection…",
  "마무리 중…": "Finishing…",
  "복사했습니다. AI 도구의 새 대화에 붙여넣으세요.": "Copied. Paste this into a new conversation in your AI tool.",
  "문구를 선택했습니다. Ctrl+C 또는 ⌘C로 복사하세요.": "Prompt selected. Press Ctrl+C or ⌘C to copy it.",
  "개발 시스템": "Development",
  "품질 시스템": "Quality",
  "사용 범위": "Access scope",
  "조회부터 시작 (기본)": "Start with read-only access (default)",
  "선택한 패키지의 변경 허용": "Allow changes in selected packages",
  "모든 패키지의 변경 허용": "Allow changes in all packages",
  "조회부터 시작하면 SAP 객체·Transport 변경, 디버거 제어와 ABAP 실행·Unit 테스트를 차단합니다. 나중에 이 화면에서 변경 범위를 선택할 수 있습니다.": "Read-only access blocks SAP object and transport changes, debugger controls, ABAP execution and Unit tests. You can choose a write scope here later.",
  "변경할 개발 패키지를 하나 이상 입력하세요. 예: Z_PACKAGE 또는 $TMP. 여러 패키지는 쉼표로 구분합니다.": "Enter at least one development package to change, such as Z_PACKAGE or $TMP. Separate multiple packages with commas.",
  "운영 시스템은 읽기 전용입니다. 개발·품질 시스템의 변경을 허용하려면 패키지를 입력하거나 모든 패키지를 명시적으로 선택하세요.": "Production systems are read only. To allow changes in development or quality, enter packages or explicitly select all packages.",
  "앱이 제공하는 실행 환경을 사용합니다. Node/npm이나 별도 CLI를 설치할 필요가 없습니다.": "Use the runtime provided by the app. No Node/npm or separate CLI installation is needed.",
  "앱이 등록을 관리합니다": "Registration is managed by the app",
  "SAP 연결 설정 확인": "Review your SAP connection",
  "이 MCP의 등록은 설치한 앱에서 관리합니다. 추가 CLI 설치나 MCP 등록은 필요하지 않습니다.": "The installing app manages this MCP registration. No extra CLI installation or MCP registration is needed.",
  "설치한 앱의 새 대화에 아래 문구를 붙여넣으세요. 실제 SAP 시스템 조회 결과로 접속을 확인하세요. 이 설정 창은 닫아도 됩니다.": "Paste the prompt below into a new conversation in the installing app. Confirm access with the actual SAP system query result. You can close this setup window.",
  "SAP 설정은 이 PC에 저장했습니다. 등록을 바꾸거나 도구를 추가하지 않았습니다.": "SAP settings are saved on this computer. No registrations were changed and no tools were added."
}
